server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://HR-WORKER
          predicates:
            - Path=/workers/**
        - id: hr-payroll
          uri: lb://HR-PAYROLL
          predicates:
            - Path=/payments/**
        - id: hr-user
          uri: lb://HR-USER
          predicates:
            - Path=/users/**
        - id: hr-oauth
          uri: lb://HR-OAUTH
          predicates:
            - Path=/oauth/users/**